env:
  global:
    - secure: eRFB+9CxFmOLeWhh0dMcdxB8pNGaRLMk45KNDFYgwF9aVW36BuiyEAiCHg712Ckc1f75eVIuJ86N3gER9OTmAre7GdOonheI6CwMYItDRtdbwMdv55lMGLsid2Z+S0AQgR2jlLjBy6HRjVozb7u/DPw3rEdjnfIOuyxM8lFq9qk=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly liblua5.1-0-dev
script:
  - make all test
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
